### ISSUE TITLE
404 when visiting "Design and Implementation of a High-Performance Distributed Web Crawler" link

### ISSUE THREAD

**Issue by zaccone** [checkcheckzz/system-design-interview#5]
When visiting "Design and Implementation of a High-Performance Distributed Web Crawler" user gets HTTP 404.

**Comment by checkcheckzz** [comment]
Hi,
I use a more useful and comprehensive resource: https://www.quora.com/How-can-I-build-a-web-crawler-from-scratch  to replace the old one.
